[package]
name = "lessf"
version = "0.1.0"
authors = ["https://github.com/b9r5"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "~2.27.0"
nix = "~0.17.0"